# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180107_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='home_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
