# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180108_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
