# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('actual_message_time', models.DateTimeField()),
                ('message_delivered', models.BooleanField(default=False)),
                ('message_delivary_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
