# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='actual_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
